### ISSUE TITLE
handle errors

### ISSUE THREAD

**Issue by ppazos** [ppazos/cabolabs-ehrserver-groovy#2]
java.lang.NullPointerException: Cannot get property 'token' on null object
        at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60)
        at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:172)
        at org.codehaus.groovy.runtime.callsite.NullCallSite.getProperty(NullCallSite.java:47)

**Comment by ppazos** [comment]
This happens when the service is offline (cant reach server).

**Comment by ppazos** [comment]
added handle for no connection, and 4xx errors
now login, commit and getEhrs return informational structures on exceptions
